import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { Vehicle, SoldVehicle, ShowroomSettings } from '../types';

export const pdfService = {
  // Generate Vehicle Spec Brochure PDF
  generateVehiclePDF(vehicle: Vehicle, settings: ShowroomSettings): void {
    const doc = new jsPDF();

    // Header banner
    doc.setFillColor(15, 23, 42); // #0f172a dark
    doc.rect(0, 0, 210, 40, 'F');

    doc.setTextColor(255, 255, 255);
    doc.setFontSize(20);
    doc.setFont('helvetica', 'bold');
    doc.text(settings.name.toUpperCase(), 14, 18);

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(`${settings.phone} | ${settings.email}`, 14, 26);
    doc.text(settings.address, 14, 32);

    // Title
    doc.setTextColor(15, 23, 42);
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.text(`VEHICLE SPECIFICATION SHEET`, 14, 52);

    doc.setLineWidth(0.5);
    doc.setDrawColor(59, 130, 246);
    doc.line(14, 56, 196, 56);

    // Vehicle Title & Price
    doc.setFontSize(14);
    doc.setTextColor(30, 41, 59);
    doc.text(vehicle.name, 14, 66);

    doc.setFontSize(16);
    doc.setTextColor(37, 99, 235); // Blue accent
    doc.text(`Price: ${settings.currency} ${vehicle.offerPrice.toLocaleString('en-IN')}`, 14, 75);

    // Table of Specs
    const tableData = [
      ['Brand', vehicle.brand, 'Year', vehicle.year.toString()],
      ['Model', vehicle.model, 'Registration No.', vehicle.registrationNumber],
      ['Variant', vehicle.variant, 'Fuel Type', vehicle.fuel],
      ['Transmission', vehicle.transmission, 'KM Driven', `${vehicle.kmDriven.toLocaleString('en-IN')} km`],
      ['Color', vehicle.color, 'Ownership', vehicle.owner],
      ['Insurance Valid Till', vehicle.insuranceDate, 'FC Valid Till', vehicle.fcDate],
      ['Status', vehicle.status, 'Listed Date', vehicle.createdAt]
    ];

    autoTable(doc, {
      startY: 82,
      head: [['Specification', 'Details', 'Specification', 'Details']],
      body: tableData,
      theme: 'striped',
      headStyles: { fillColor: [30, 41, 59], textColor: [255, 255, 255] },
      styles: { fontSize: 10 }
    });

    // Features Section
    let currentY = (doc as any).lastAutoTable.finalY + 12;
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(15, 23, 42);
    doc.text('Key Features & Equipment:', 14, currentY);

    currentY += 6;
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(51, 65, 85);

    const featureText = vehicle.features.join('  •  ');
    doc.text(`• ${featureText}`, 14, currentY, { maxWidth: 180 });

    // Description Section
    currentY += 15;
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(15, 23, 42);
    doc.text('Vehicle Overview:', 14, currentY);

    currentY += 6;
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(51, 65, 85);
    doc.text(vehicle.description, 14, currentY, { maxWidth: 180 });

    // Footer
    doc.setFontSize(8);
    doc.setTextColor(148, 163, 184);
    doc.text(`Generated by AutoMatrix System on ${new Date().toLocaleDateString()} | Confidential Spec Sheet`, 14, 285);

    doc.save(`${vehicle.name.replace(/\s+/g, '_')}_Specification.pdf`);
  },

  // Generate Sales Invoice PDF
  generateInvoicePDF(soldRecord: SoldVehicle, settings: ShowroomSettings): void {
    const doc = new jsPDF();

    // Dark Header
    doc.setFillColor(15, 23, 42);
    doc.rect(0, 0, 210, 45, 'F');

    doc.setTextColor(255, 255, 255);
    doc.setFontSize(22);
    doc.setFont('helvetica', 'bold');
    doc.text(settings.name, 14, 20);

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(`${settings.phone}  |  ${settings.email}`, 14, 28);
    doc.text(settings.address, 14, 34);

    // Invoice Label
    doc.setFontSize(20);
    doc.setFont('helvetica', 'bold');
    doc.text('VEHICLE SALES INVOICE', 120, 22);

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(`Invoice No: INV-${soldRecord.id.toUpperCase()}`, 120, 30);
    doc.text(`Date: ${soldRecord.soldAt}`, 120, 36);

    // Customer & Vehicle Info Grid
    let currentY = 55;

    doc.setTextColor(15, 23, 42);
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.text('BUYER DETAILS', 14, currentY);
    doc.text('VEHICLE DETAILS', 110, currentY);

    doc.setLineWidth(0.5);
    doc.setDrawColor(226, 232, 240);
    doc.line(14, currentY + 2, 196, currentY + 2);

    currentY += 8;
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(51, 65, 85);

    doc.text(`Name: ${soldRecord.customerName}`, 14, currentY);
    doc.text(`Vehicle: ${soldRecord.vehicleName}`, 110, currentY);

    currentY += 6;
    doc.text(`Phone: ${soldRecord.customerPhone}`, 14, currentY);
    doc.text(`Brand: ${soldRecord.brand}`, 110, currentY);

    currentY += 6;
    doc.text(`Sales Exec: ${soldRecord.salesExecutive}`, 14, currentY);
    doc.text(`Reg No: ${soldRecord.registrationNumber}`, 110, currentY);

    currentY += 6;
    doc.text(`Delivery Date: ${soldRecord.deliveryDate}`, 14, currentY);
    doc.text(`Payment Mode: ${soldRecord.paymentMethod}`, 110, currentY);

    // Payment Table
    const paymentRows = [
      ['Vehicle Listing Price', `${settings.currency} ${soldRecord.originalPrice.toLocaleString('en-IN')}`],
      ['Special Discount Offered', `- ${settings.currency} ${soldRecord.discount.toLocaleString('en-IN')}`],
      ['Final Sale Price', `${settings.currency} ${soldRecord.salePrice.toLocaleString('en-IN')}`]
    ];

    autoTable(doc, {
      startY: currentY + 12,
      head: [['Description', 'Amount']],
      body: paymentRows,
      theme: 'grid',
      headStyles: { fillColor: [30, 41, 59], textColor: [255, 255, 255] },
      styles: { fontSize: 10, cellPadding: 4 }
    });

    currentY = (doc as any).lastAutoTable.finalY + 15;

    // Total Highlight Box
    doc.setFillColor(241, 245, 249);
    doc.rect(14, currentY, 182, 18, 'F');

    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(15, 23, 42);
    doc.text(`TOTAL AMOUNT PAID:`, 20, currentY + 12);

    doc.setTextColor(37, 99, 235);
    doc.setFontSize(14);
    doc.text(`${settings.currency} ${soldRecord.salePrice.toLocaleString('en-IN')}`, 130, currentY + 12);

    // Remarks
    currentY += 28;
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(15, 23, 42);
    doc.text('Remarks / Terms:', 14, currentY);

    currentY += 6;
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(71, 85, 105);
    doc.text(soldRecord.remarks || 'Vehicle sold in certified pre-owned condition.', 14, currentY, { maxWidth: 180 });

    // Signatures
    currentY += 35;
    doc.setLineWidth(0.5);
    doc.setDrawColor(203, 213, 225);
    doc.line(14, currentY, 70, currentY);
    doc.line(130, currentY, 190, currentY);

    doc.setFontSize(9);
    doc.setTextColor(100, 116, 139);
    doc.text('Customer Signature', 22, currentY + 5);
    doc.text('Authorized Representative', 138, currentY + 5);

    doc.save(`Invoice_${soldRecord.customerName.replace(/\s+/g, '_')}_${soldRecord.id}.pdf`);
  }
};
